language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls --quiet

before_script:
  - sh create_db.sh

# command to run tests
script: coverage run --source=app ./manage.py test
after_success: coveralls
