language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls --quiet

before_script:
  - export FLASK_DEBUG=1
  - export FLASK_APP="run.py"
  - export APP_SETTINGS="development"
  - export SECRET="openthesea"
  - export DATABASE_URL='sqlite:///app.db'
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade
  - python -m flask run

# command to run tests
script: coverage run --source=app ./manage.py test
after_success: coveralls
